default_language_version:
  python: python3

repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.12.11
    hooks:
    - id: ruff
      args: ["--fix", "--ignore=F722,F821"]
    - id: ruff-format